version: '3.8'

services:
  # MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data

  # Redis - Deduplication
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  subscriber:
    build: .
    depends_on:
      - mosquitto
      - redis
    environment:
      - MQTT_URL=mqtt://mosquitto:1883
      - REDIS_HOST=redis
    restart: always